version: "3.2"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - 3000:3000
  hello_bot:
    build: ./webex-bot
    container_name: hello_bot
    ports:
      - 5001:4040
      - 5002:5000
    volumes:
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/webex-bot/hello_bot:/workspace
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/webex-bot/helpers:/workspace/helpers
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/webex-bot/config:/opt/config
    entrypoint: /workspace/run.sh
    tty: true
    environment:
      - PYTHONPATH=/workspace/
