version: "3.2"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - 3000:3000
  emotebot:
    build: ./emotebot
    container_name: emotebot
    ports:
      - 5001:4040
      - 5002:5000
    volumes:
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/emotebot/emotebot:/workspace
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/emotebot/helpers:/workspace/helpers
      - C:/Users/Yong Shen/Desktop/Repositories/supreme-palm-tree/emotebot/config:/opt/config
    entrypoint: /workspace/run.sh
    tty: true
    environment:
      - PYTHONPATH=/workspace/
